### ISSUE TITLE
Is there a sample app that demonstrates user typing text that has been defined by a syntax module?

### ISSUE THREAD

**Issue by rcammarere** [JetBrains/Nitra#33]
Disregard this issue.  I guess SimpleSharp is my best bet to learning how to define syntax.

**Comment by rcammarere** [comment]
I've tried testing with "SimpleSharp", but I don't think I'm using it correctly.  The command prompt dissappears every time I hit the enter key after typing.

**Comment by VladD2** [comment]
I do not understand your question.
You can test a compiled grammar (syntax modules) in Nitra.Visualizer.exe. With Nitra supplied such grammar as the JSON, CSharp and Nitra. You need to create TestSuit for one of them and enter the text in the text box on the right side of Nitra.Visualizer.exe.

**Comment by rcammarere** [comment]
That's why I decided to tell you to disregard this question.  I'm still trying to wrap my brain around all of this to see how I can get it to work for what I want to do with it (see Issue #32).
