### ISSUE TITLE
Import of Antlr grammars for reuse

### ISSUE THREAD

**Issue by sirinath** [JetBrains/Nitra#35]
Add a feature so you can reuse Antlr grammar definitions.

**Comment by rampelstinskin** [comment]
Will not happen.
Nitra parsing algorithm too different.

**Comment by VladD2** [comment]
This does not prevent import of ANTLR grammars with little manual rework.

**Comment by VladD2** [comment]
Sirinath. Maybe you try yourself to write such a converter?

**Comment by sirinath** [comment]
This is not my strong suite but there a lot of grammars written in ANTLR. Iff we can just import them it will make life a lot easier than re implementing from scratch.
